apiVersion: v1
kind: Service
metadata:
  name: voting-front-service
  labels:
    name: voting-front-service
    app: azure-voting-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    name: voting-front-pod
    app: azure-voting-app