apiVersion: v1
kind: Service
metadata:
  name: voting-front-service
  labels:
    name: voting-front-service
    app: azure-voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    name: voting-front-pod
    app: azure-voting-app